var w = window.innerWidth;
var h = window.innerHeight;
var largura = ((w-50)/4);
console.log('Altura='+h)
console.log('Largura='+w)
var l = largura.toString();
   document.getElementById('col1').style.minWidth=l+'px';
   document.getElementById('col2').style.minWidth=l+'px';
   document.getElementById('col3').style.minWidth=l+'px';
   document.getElementById('col4').style.minWidth=l+'px';